package com.db.awmd.challenge.validator;

public enum TransferErrorCode {

    ACCOUNT_FROM_ID_IS_NULL,
    ACCOUNT_FROM_ID_NOT_FOUND,
    ACCOUNT_FROM_ID_DO_NOT_HAVE_ENOUGH_MONEY,

    ACCOUNT_TO_ID_IS_NULL,
    ACCOUNT_TO_ID_NOT_FOUND,

    TRANSFER_TO_THE_SAME_ACCOUNT,

    AMOUNT_TO_TRANSFER_IS_NULL,
    AMOUNT_TO_TRANSFER_IS_NEGATIVE_OR_ZERO;
}
